### PR TITLE
[:green_heart:] 6주차_Heap 공부 완료

### PR DESCRIPTION
**Pull request by haeun-noh**

### CODE REVIEW

**Review by leeda06 — COMMENTED** [review]
[힙]
1. X
2. X
3. X
4. O

**Comment by mic050r** [comment]
1. O
2. O
3. X
4. O

**Review by huihyeon06 — COMMENTED** [review]
1. O
2. X
3. X
4. O

**Review by haeun-noh — COMMENTED** [review]
[정답]
1. O
2. X
3. X
4. X

**Pull request merged**
